name: Release

on:
  workflow_dispatch:

jobs:
  version:
    name: "Release"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
      - name: Install python-semantic-release
        run: pip install python-semantic-release
      - name: Generate version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: set-version
        run: |
          export GIT_COMMIT_AUTHOR="GitHub Actions <actions@github.com>"
          semantic-release version
