name: Release

on:
  workflow_dispatch:

jobs:
  version:
    name: "Release"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"
      - name: Install python-semantic-release
        run: pip install python-semantic-release
      - name: Generate version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: set-version
        run: |
          export GIT_COMMIT_AUTHOR="GitHub Actions <actions@github.com>"
          semantic-release version
